version: 2.1

jobs:
  build:
    resource_class: large
    docker:
      - image: 168867913376.dkr.ecr.eu-west-1.amazonaws.com/docker-java-build:22
    working_directory: ~/repo

    steps:
      - checkout
      - run: mvn clean install -DbuildNumber=<< pipeline.number >> -DbranchName=<< pipeline.git.branch >>
      - run: mvn deploy -DbuildNumber=<< pipeline.number >> -DbranchName=<< pipeline.git.branch >>

workflows:
  version: 2
  build-and-deploy-to-maven-repo:
    jobs:
      - build:
          context: dev.mynt.se